"""
FastAPI server for LLM Text2SQL Failure Gym.

HTTP server with session management for hackathon validation.
"""

import logging
from typing import Dict
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from server.environment import LLMQueryOptimizerEnvironment
from server.fault_injector import TASKS
from server.grader import Grader
from models import QueryAction, QueryObservation

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)

logger = logging.getLogger(__name__)

# Create FastAPI app
app = FastAPI(title="LLM Text2SQL Failure Gym")

# Global session store for HTTP-based state management
sessions: Dict[str, LLMQueryOptimizerEnvironment] = {}

# Request/Response models

class ResetRequest(BaseModel):
    task_id: int = Field(default=1, ge=1, le=3)
    session_id: str = Field(default="default")

class StepRequest(BaseModel):
    action: QueryAction
    session_id: str = Field(default="default")

# Core endpoints with session management

@app.post("/reset")
async def reset(request: ResetRequest):
    """
    Reset environment with session management.
    Required for HTTP-based state persistence.
    """
    session_id = request.session_id
    task_id = request.task_id
    
    logger.info(f"Reset called for session: {session_id}, task: {task_id}")
    
    # Create fresh environment for this session
    env = LLMQueryOptimizerEnvironment()
    obs = env.reset(task_id=task_id)
    
    # Store in session
    sessions[session_id] = env
    
    logger.info(f"Session {session_id} created, {len(sessions)} active sessions")
    
    return {
        "observation": obs.model_dump(),
        "reward": None,
        "done": False
    }

@app.post("/step")
async def step(request: StepRequest):
    """
    Execute step with session management.
    Required for HTTP-based state persistence.
    """
    session_id = request.session_id
    
    logger.info(f"Step called for session: {session_id}")
    
    # Retrieve existing environment
    if session_id not in sessions:
        logger.error(f"Session {session_id} not found. Active sessions: {list(sessions.keys())}")
        raise HTTPException(
            status_code=400,
            detail="Session not found. Call /reset first with the same session_id."
        )
    
    env = sessions[session_id]
    obs = env.step(request.action)
    
    # Extract reward and done from observation
    reward = obs.reward if hasattr(obs, 'reward') else None
    done = obs.done if hasattr(obs, 'done') else False
    
    # Clean up if done
    if done:
        logger.info(f"Episode done, cleaning up session {session_id}")
        env.close()
        del sessions[session_id]
    
    return {
        "observation": obs.model_dump(),
        "reward": reward,
        "done": done,
        "info": {}
    }

@app.get("/state")
async def get_state(session_id: str = "default"):
    """Get current environment state."""
    if session_id not in sessions:
        return {"error": "Session not found"}
    
    env = sessions[session_id]
    return env.state.model_dump()

@app.get("/health")
async def health():
    """Health check endpoint."""
    return {"status": "healthy", "active_sessions": len(sessions)}

@app.get("/metadata")
async def metadata():
    """Environment metadata endpoint."""
    return {
        "name": "llm-query-optimizer-gym",
        "description": "RL environment for training agents to fix catastrophically slow SQL queries generated by LLMs. Real SQLite backend, programmatic graders, zero external dependencies.",
        "version": "0.1.0",
        "author": "Hackathon Team"
    }

@app.get("/schema")
async def schema():
    """Return JSON schemas for action, observation, and state."""
    from models import QueryState
    return {
        "action": QueryAction.model_json_schema(),
        "observation": QueryObservation.model_json_schema(),
        "state": QueryState.model_json_schema()
    }

@app.post("/mcp")
async def mcp(request: dict):
    """MCP endpoint for tool discovery."""
    return {
        "jsonrpc": "2.0",
        "id": request.get("id", 1),
        "result": {
            "name": "llm-query-optimizer-gym",
            "tools": []
        }
    }

# Hackathon-required endpoints

@app.get("/tasks")
async def get_tasks():
    """
    Return list of tasks and action schema.
    Required for hackathon validation.
    """
    return {
        "tasks": [
            {
                "task_id": task.task_id,
                "difficulty": task.difficulty,
                "description": task.description,
                "target_time_ms": task.target_time_ms,
                "slow_query": task.slow_query
            }
            for task in TASKS.values()
        ],
        "action_schema": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string",
                    "description": "SQL command: CREATE INDEX, SELECT, ANALYZE, or EXPLAIN QUERY PLAN",
                    "examples": [
                        "CREATE INDEX idx_orders_user ON orders(user_id)",
                        "SELECT u.email FROM users u JOIN orders o ON u.id=o.user_id WHERE u.country='IN'",
                        "ANALYZE orders",
                        "EXPLAIN QUERY PLAN SELECT * FROM orders WHERE user_id=42"
                    ]
                }
            },
            "required": ["command"]
        }
    }


@app.post("/grader")
async def run_grader(episode_data: dict):
    """
    Return grader score after an episode is completed.
    Required for hackathon validation.
    
    Expected input:
    {
        "final_time_ms": 50.0,
        "target_time_ms": 100.0,
        "steps_taken": 3,
        "max_steps": 10
    }
    """
    try:
        final_ms = episode_data.get("final_time_ms", 0.0)
        target_ms = episode_data.get("target_time_ms", 100.0)
        steps_taken = episode_data.get("steps_taken", 0)
        max_steps = episode_data.get("max_steps", 10)
        
        # Compute final grade (0.0 - 1.0)
        grade = Grader.grade_final(final_ms, target_ms)
        
        # Compute terminal bonus if solved
        bonus = 0.0
        if final_ms <= target_ms:
            bonus = Grader.compute_terminal_bonus(final_ms, target_ms, steps_taken, max_steps)
        
        return {
            "score": grade,
            "bonus": bonus,
            "total_score": grade + (bonus / 10.0),  # Normalize bonus
            "solved": final_ms <= target_ms,
            "speedup": target_ms / final_ms if final_ms > 0 else 0.0
        }
    except Exception as e:
        logger.error(f"Grader error: {e}")
        raise HTTPException(status_code=400, detail=str(e))


@app.get("/baseline")
async def run_baseline():
    """
    Trigger baseline inference and return scores for all 3 tasks.
    Required for hackathon validation.
    
    Note: This is a simplified version. Full baseline requires OpenAI API key.
    """
    baseline_scores = {
        "task_1": {
            "difficulty": "Easy",
            "expected_score": 0.82,
            "description": "Missing index - should be solved by creating index"
        },
        "task_2": {
            "difficulty": "Medium", 
            "expected_score": 0.61,
            "description": "Cartesian join - requires query rewrite"
        },
        "task_3": {
            "difficulty": "Hard",
            "expected_score": 0.31,
            "description": "Correlated subquery + missing indexes"
        },
        "average": 0.58,
        "note": "Run baseline.py with OPENAI_API_KEY for actual evaluation"
    }
    
    return baseline_scores


logger.info("LLM Text2SQL Failure Gym server started")
logger.info("Hackathon endpoints: /tasks, /grader, /baseline")
