"""
LLM Text2SQL Failure Gym Environment Implementation.

Agent fixes catastrophically slow SQL queries generated by LLMs.
Real SQLite backend, programmatic graders, zero external dependencies.
"""

import logging
import os
import threading
from uuid import uuid4
from typing import Optional

from openenv.core.env_server.interfaces import Environment

from models import QueryAction, QueryObservation, QueryState
from server.sqlite_backend import SQLiteBackend
from server.fault_injector import FaultInjector
from server.grader import Grader

logger = logging.getLogger(__name__)


class LLMQueryOptimizerEnvironment(Environment):
    """
    OpenEnv environment for training agents to fix slow SQL queries.
    
    The agent receives a slow query and must optimize it through:
    - Creating indexes
    - Rewriting queries
    - Analyzing tables
    
    All metrics are objective and deterministic (no LLM judge needed).
    
    Uses a shared database across all instances for performance.
    """
    
    SUPPORTS_CONCURRENT_SESSIONS: bool = False
    MAX_STEPS: int = 10
    
    # Class-level shared database (created once, reused by all instances)
    _shared_backend: Optional[SQLiteBackend] = None
    _backend_lock = threading.Lock()
    
    def __init__(self):
        """Initialize the environment."""
        try:
            logger.info(f"Initializing LLMQueryOptimizerEnvironment (id={id(self)})...")
            
            # Initialize or reuse shared backend
            with self._backend_lock:
                if LLMQueryOptimizerEnvironment._shared_backend is None:
                    db_path = os.environ.get("DB_PATH")
                    seed = int(os.environ.get("RANDOM_SEED", "42"))
                    LLMQueryOptimizerEnvironment._shared_backend = SQLiteBackend(
                        db_path=db_path, seed=seed
                    )
                    # Create database once - this is the expensive operation
                    LLMQueryOptimizerEnvironment._shared_backend.create_and_seed_db()
                    logger.info("Shared database created and seeded (100K users, 200K orders, 500K items)")
                else:
                    logger.info("Reusing existing shared database")
                
                self.backend = LLMQueryOptimizerEnvironment._shared_backend
            
            # Initialize fault injector and grader (per-instance)
            self.injector = FaultInjector(self.backend)
            self.grader = Grader()
            
            # Episode state (per-instance)
            self.current_task: Optional[dict] = None
            self.step_count: int = 0
            self.action_history: list[str] = []
            self.baseline_time_ms: float = 0.0
            self.current_time_ms: float = 0.0
            self.target_time_ms: float = 0.0
            self.cumulative_reward: float = 0.0
            
            # State tracking
            self._state = QueryState(episode_id=str(uuid4()))
            
            logger.info(f"LLMQueryOptimizerEnvironment initialized successfully (id={id(self)})")
            
        except Exception as e:
            logger.error(f"FATAL: Environment initialization failed: {e}", exc_info=True)
            raise
    
    def reset(self, seed: Optional[int] = None, episode_id: Optional[str] = None, task_id: int = 1, **kwargs) -> QueryObservation:
        """
        Reset environment and inject fault for specified task.
        
        Args:
            seed: Random seed (OpenEnv standard parameter)
            episode_id: Episode identifier (OpenEnv standard parameter)
            task_id: Task ID (1=easy, 2=medium, 3=hard)
            **kwargs: Additional parameters
        
        Returns:
            Initial observation
        """
        logger.info(f"reset() called with task_id={task_id}, seed={seed}, episode_id={episode_id} on env id={id(self)}")
        
        try:
            # DON'T recreate database - just inject fault
            # The shared database is already created and seeded
            self.current_task = self.injector.inject_fault(task_id)
            
            # Reset episode state
            self.step_count = 0
            self.action_history = []
            self.baseline_time_ms = self.current_task["baseline_time_ms"]
            self.current_time_ms = self.baseline_time_ms
            self.target_time_ms = self.current_task["target_time_ms"]
            self.cumulative_reward = 0.0
            
            # Update state
            self._state = QueryState(
                episode_id=str(uuid4()),
                task_id=task_id,
                baseline_time_ms=self.baseline_time_ms,
                current_time_ms=self.current_time_ms,
                target_time_ms=self.target_time_ms,
                steps_taken=0,
                is_solved=False,
                cumulative_reward=0.0,
                commands_history=[]
            )
            
            logger.info(
                f"Episode reset: task={task_id}, "
                f"baseline={self.baseline_time_ms:.2f}ms, "
                f"target={self.target_time_ms:.2f}ms"
            )
            
            # Return initial observation
            return QueryObservation(
                task_id=task_id,
                task_description=self.current_task["description"],
                slow_query=self.current_task["slow_query"],
                execution_time_ms=self.baseline_time_ms,
                query_plan=self.current_task["query_plan"],
                command_output=(
                    f"Task {task_id} ({self.current_task['difficulty']}): "
                    f"{self.current_task['description']}\n\n"
                    f"Slow Query:\n{self.current_task['slow_query']}\n\n"
                    f"Current execution time: {self.baseline_time_ms:.2f}ms\n"
                    f"Target: {self.target_time_ms:.2f}ms\n\n"
                    f"Optimize this query using CREATE INDEX, query rewriting, or ANALYZE."
                ),
                history=[],
                step=0,
                max_steps=self.MAX_STEPS,
                reward_breakdown={}
            )
            
        except Exception as e:
            logger.error(f"reset() failed: {e}", exc_info=True)
            # Return safe default observation
            return QueryObservation(
                task_id=1,
                task_description="Error during reset",
                slow_query="",
                execution_time_ms=0.0,
                query_plan="",
                command_output=f"Error: {str(e)}",
                history=[],
                step=0,
                max_steps=self.MAX_STEPS,
                reward_breakdown={}
            )
    
    def step(self, action: QueryAction) -> QueryObservation:
        """
        Execute one optimization step.
        
        Args:
            action: SQL command to execute
        
        Returns:
            Observation with results and reward
        """
        logger.info(f"step() called on env id={id(self)}, current_task={'set' if self.current_task else 'None'}")
        
        # Check if environment has been reset
        if self.current_task is None:
            logger.error("step() called before reset()")
            return QueryObservation(
                task_id=1,
                task_description="Error: Environment not initialized",
                slow_query="",
                execution_time_ms=0.0,
                query_plan="",
                command_output="Error: Please call reset() before step()",
                history=[],
                step=0,
                max_steps=self.MAX_STEPS,
                reward_breakdown={"total": -0.5, "error_penalty": -0.5},
                done=False,
                reward=-0.5
            )
        
        self.step_count += 1
        command = action.command.strip()
        
        logger.info(f"Step {self.step_count}/{self.MAX_STEPS}: {command[:100]}")
        
        try:
            # Record action in history
            self.action_history.append(command)
            
            # Store previous time for reward calculation
            previous_time_ms = self.current_time_ms
            
            # Execute command
            output, exec_time_ms, query_plan = self.backend.run_command(command)
            
            # If command was a SELECT query, update current time
            if command.upper().startswith("SELECT"):
                self.current_time_ms = exec_time_ms
            else:
                # For other commands (CREATE INDEX, etc.), re-measure the slow query
                self.current_time_ms = self.backend.measure_query_time(
                    self.current_task["slow_query"]
                )
                query_plan = self.backend.get_query_plan(
                    self.current_task["slow_query"]
                )
            
            # Compute reward
            reward_breakdown = self.grader.compute_reward(
                before_ms=previous_time_ms,
                after_ms=self.current_time_ms,
                query_plan=query_plan,
                action_history=self.action_history
            )
            
            reward = reward_breakdown["total"]
            
            # Check if task is solved
            done = False
            if self.current_time_ms <= self.target_time_ms:
                # Task solved! Add terminal bonus
                terminal_bonus = self.grader.compute_terminal_bonus(
                    final_ms=self.current_time_ms,
                    target_ms=self.target_time_ms,
                    steps_taken=self.step_count,
                    max_steps=self.MAX_STEPS
                )
                reward += terminal_bonus
                reward_breakdown["terminal_bonus"] = terminal_bonus
                done = True
                logger.info(
                    f"Task solved! Final time: {self.current_time_ms:.2f}ms "
                    f"(target: {self.target_time_ms:.2f}ms), "
                    f"bonus: +{terminal_bonus:.2f}"
                )
            
            # Check if max steps reached
            if self.step_count >= self.MAX_STEPS:
                done = True
                if self.current_time_ms > self.target_time_ms:
                    logger.info(
                        f"Max steps reached. Task not solved. "
                        f"Final: {self.current_time_ms:.2f}ms, "
                        f"Target: {self.target_time_ms:.2f}ms"
                    )
            
            # Update cumulative reward
            self.cumulative_reward += reward
            
            # Update state
            self._state.steps_taken = self.step_count
            self._state.current_time_ms = self.current_time_ms
            self._state.is_solved = (self.current_time_ms <= self.target_time_ms)
            self._state.cumulative_reward = self.cumulative_reward
            self._state.commands_history = self.action_history.copy()
            
            logger.info(
                f"  Result: time={self.current_time_ms:.2f}ms, "
                f"reward={reward:.4f}, done={done}"
            )
            
            # Build observation
            observation = QueryObservation(
                task_id=self.current_task["task_id"],
                task_description=self.current_task["description"],
                slow_query=self.current_task["slow_query"],
                execution_time_ms=self.current_time_ms,
                query_plan=query_plan,
                command_output=output,
                history=self.action_history.copy(),
                step=self.step_count,
                max_steps=self.MAX_STEPS,
                reward_breakdown=reward_breakdown,
                done=done,
                reward=reward
            )
            
            return observation
            
        except Exception as e:
            logger.error(f"step() failed: {e}", exc_info=True)
            # Return safe observation with penalty
            return QueryObservation(
                task_id=self.current_task["task_id"] if self.current_task else 1,
                task_description=self.current_task["description"] if self.current_task else "",
                slow_query=self.current_task["slow_query"] if self.current_task else "",
                execution_time_ms=self.current_time_ms,
                query_plan="",
                command_output=f"Error: {str(e)}",
                history=self.action_history.copy(),
                step=self.step_count,
                max_steps=self.MAX_STEPS,
                reward_breakdown={"total": -0.5, "error_penalty": -0.5},
                done=False,
                reward=-0.5
            )
    
    @property
    def state(self) -> QueryState:
        """Return current environment state."""
        return self._state
    
    def close(self):
        """Clean up resources. Don't close shared backend."""
        # Don't close the shared backend - it's reused across instances
        logger.info(f"Environment instance {id(self)} closed (shared backend remains active)")
